EV-test/Models/Patient.cs
using System;
using System.Collections.Generic;

namespace EV_test.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public string PatientName { get; set; } = null!;

    public DateOnly DateOfBirth { get; set; }

    public string Phone { get; set; } = null!;

    public string? Image { get; set; }

    public bool Emergency { get; set; }

    public virtual ICollection<PatientReport> PatientReports { get; set; } = new List<PatientReport>();
}

EV-test/Controllers/PatientsController.cs
using EV_test.Models.ViewModel;
using EV_test.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EV_test.Controllers
{
    public class PatientsController : Controller
    {
        private readonly IWebHostEnvironment _he;
        private readonly PatientDbContext _context;
        public PatientsController(IWebHostEnvironment _he, PatientDbContext _context)
        {
            this._context = _context;
            this._he = _he;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _context.Patients.Include(x => x.PatientReports).ThenInclude(y => y.Report).ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult AddNewSkills(int? id)
        {
            ViewBag.skill = new SelectList(_context.Reports, "ReportId", "ReportName", id.ToString() ?? "");
            return PartialView("_AddNewSkills");
        }
        [HttpPost]
        public async Task<IActionResult> Create(PatientVM VM, int[] ReportId)
        {
            if (ModelState.IsValid)
            {
                Patient patient = new Patient()
                {
                    PatientName = VM.PatientName,
                    DateOfBirth = VM.DateOfBirth,
                    Phone = VM.Phone,
                    Emergency = VM.Emergency
                };
                //image
                var file = VM.ImagePath;
                string webroot = _he.WebRootPath;
                string folder = "Images";
                string imgFileName = DateTime.Now.Ticks.ToString() + "_" + Path.GetFileName(VM.ImagePath.FileName);
                string fileToSave = Path.Combine(webroot, folder, imgFileName);

                if (file != null)
                {
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        VM.ImagePath.CopyTo(stream);
                        patient.Image = "/" + folder + "/" + imgFileName;
                    }
                }
                foreach (var item in ReportId)
                {
                    PatientReport patientReport = new PatientReport()
                    {
                        Patient = patient,
                        PatientId = patient.PatientId,
                        ReportId = item
                    };
                    _context.PatientReports.Add(patientReport);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            var patient = await _context.Patients.FirstOrDefaultAsync(x => x.PatientId == id);

            PatientVM VM = new PatientVM()
            {
                PatientId = patient.PatientId,
                PatientName = patient.PatientName,
                DateOfBirth = patient.DateOfBirth,
                Phone = patient.Phone,
                Image = patient.Image,
                Emergency = patient.Emergency
            };
            var existReport = _context.PatientReports.Where(x => x.PatientId == id).ToList();
            foreach (var item in existReport)
            {
                VM.ReportList.Add(item.ReportId);
            }
            return View(VM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PatientVM VM, int[] ReportId)
        {
            if (ModelState.IsValid)
            {
                Patient patient = new Patient()
                {
                    PatientId = VM.PatientId,
                    PatientName = VM.PatientName,
                    DateOfBirth = VM.DateOfBirth,
                    Phone = VM.Phone,
                    Emergency = VM.Emergency,
                    Image = VM.Image
                };
                var file = VM.ImagePath;
                string existImg = VM.Image;

                if (file != null)
                {
                    string webroot = _he.WebRootPath;
                    string folder = "Images";
                    string imgFileName = DateTime.Now.Ticks.ToString() + "_" + Path.GetFileName(VM.ImagePath.FileName);
                    string fileToSave = Path.Combine(webroot, folder, imgFileName);
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        VM.ImagePath.CopyTo(stream);
                        patient.Image = "/" + folder + "/" + imgFileName;
                    }

                }
                else
                {
                    patient.Image = existImg;
                }

                var existReport = _context.PatientReports.Where(x => x.PatientId == patient.PatientId).ToList();
                //Remove
                foreach (var item in existReport)
                {
                    _context.PatientReports.Remove(item);
                }
                //Add
                foreach (var item in ReportId)
                {
                    PatientReport patientReport = new PatientReport()
                    {
                        PatientId = patient.PatientId,
                        ReportId = item
                    };
                    _context.PatientReports.Add(patientReport);
                }
                _context.Update(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            var patient = await _context.Patients.FirstOrDefaultAsync(x => x.PatientId == id);
            var existReport = _context.PatientReports.Where(x => x.PatientId == id).ToList();
            foreach (var item in existReport)
            {
                _context.PatientReports.Remove(item);
            }

            _context.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

EV-test/Views/Patients/Create.cshtml
@model EV_test.Models.ViewModel.PatientVM

@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div class="row d-flex justify-content-between">
                <div class="col-6">
                    <h3>Patient</h3>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="PatientName" class="control-label"></label>
                        <input asp-for="PatientName" class="form-control form-control-sm" />
                        <span asp-validation-for="PatientName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="control-label"></label>
                        <input asp-for="DateOfBirth" class="form-control form-control-sm" type="date" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control form-control-sm" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ImagePath" class="control-label"></label>
                        <input asp-for="ImagePath" class="form-control form-control-sm" type="file" />
                        <span asp-validation-for="ImagePath" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Emergency" /> @Html.DisplayNameFor(model => model.Emergency)
                        </label>
                    </div>
                    <div class="form-group d-flex justify-content-end">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
                <div class="col-6">
                    <h3>Add Reports</h3>
                    <div class="d-flex justify-content-end">
                        <a id="btnPlus" class="btn btn-primary btn-sm mb-2">Add</a>
                    </div>
                    <div id="skillContainer">
                        <script>
                            LoadData();
                        </script>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EV-test/Views/Patients/Edit.cshtml
@model EV_test.Models.ViewModel.PatientVM
@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div class="row d-flex justify-content-between">
                <div class="col-6">
                    <h3>Edit Candidate</h3>
                    <input asp-for="PatientId" type="hidden" />
                    <input asp-for="Image" type="hidden" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="PatientName" class="control-label"></label>
                        <input asp-for="PatientName" class="form-control form-control-sm" />
                        <span asp-validation-for="PatientName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="control-label"></label>
                        <input asp-for="DateOfBirth" class="form-control form-control-sm" type="date" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control form-control-sm" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ImagePath" class="control-label"></label>
                        <input asp-for="ImagePath" class="form-control form-control-sm" type="file" />
                        <img src="@Model.Image" width="100" height="100"  />
                        <span asp-validation-for="ImagePath" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Emergency" /> @Html.DisplayNameFor(model => model.Emergency)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-6">
                    <h3>Add Reports</h3>
                    <div class="d-flex justify-content-end">
                        <a id="btnPlus" class="btn btn-primary btn-sm mb-2">Add More</a>
                    </div>
                    <div id="skillContainer">
                        @foreach (var item in Model.ReportList)
                        {
                            <script>
                                LoadData(@item);
                            </script>
                        }

                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EV-test/Views/Patients/Index.cshtml
@model IEnumerable<EV_test.Models.Patient>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <h3>Patient List</h3>
    <div class="col">
        <div class="d-flex justify-content-end">
            <a class="btn btn-primary btn-sm mb-2" asp-action="Create" asp-controller="Patients">Add New Patient</a>
        </div>
        @foreach (var item in Model)
        {
            <div class="card mb-4 bg-info">
                <div class="card-header d-flex justify-content-between">
                    <div>
                        <img src="@item.Image" width="60" height="60" />
                        <b>Name :</b> @Html.DisplayFor(x => item.PatientName)&nbsp;| &nbsp;
                        <b>Date of Birth :</b> @Html.DisplayFor(x => item.DateOfBirth)&nbsp;| &nbsp;
                        <b>Phone :</b> @Html.DisplayFor(x => item.Phone)&nbsp;| &nbsp;
                        <b>Emergency :</b> @Html.DisplayFor(x => item.Emergency)
                    </div>
                    <div>
                        <a asp-action="Edit" asp-controller="Patients" class="btn btn-success" asp-route-id="@item.PatientId">Edit</a>
                        <a asp-action="Delete" class="btn btn-danger" asp-controller="Patients" asp-route-id="@item.PatientId">Delete</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr class="fw-bold">
                                <th>Report Id</th>
                                <th>Reports</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var i in item.PatientReports)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(x => i.ReportId)</td>
                                    <td>@Html.DisplayFor(x => i.Report.ReportName)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }
    </div>
</div>

EV-test/Views/Patients/_AddNewSkills.cshtml
@model EV_test.Models.Report
<div class="d-flex justify-content-between">
    <div class="col-10 mb-2">
        @Html.DropDownListFor(x => x.ReportId, ViewBag.skill as SelectList, "----Select----", new { @class = "form-select form-select-sm" })
    </div>
    <div class="col-2">
        <a id="deleteSkill" class="btn btn-danger btn-sm ms-2">x</a>
    </div>
</div>